# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore -r linux-arm

# copy everything else and build app
COPY *.cs* app*.json ./ 
# calling copy in this mannor seems to be the only way
# to prevent directory flattening
# https://github.com/moby/moby/issues/15858
COPY Controllers/ ./Controllers/
COPY Hubs/ ./Hubs/
COPY Infrastructure/ ./Infrastructure/
COPY Migrations/ ./Migrations/
COPY Model/ ./Model/
COPY Services/ ./Services/
COPY ViewModels/ ./ViewModels/

RUN dotnet publish -c release -o /app -r linux-arm --self-contained true

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:8.0-bookworm-slim-arm32v7

LABEL maintainer="lassi@heisl.org"
LABEL version="0.1"
LABEL description="multiplayer shopping list"

WORKDIR /app
COPY --from=build /app ./
COPY ClientApp/dist/ ./wwwroot

# See: https://github.com/dotnet/announcements/issues/20
# Uncomment to enable globalization APIs (or delete)
#ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
#RUN apk add --no-cache icu-libs
#ENV LC_ALL=en_US.UTF-8
#ENV LANG=en_US.UTF-8

ENTRYPOINT ["./mps"]
